export default {
  AIRTABLE_DATABASE_ID: process.env.REACT_APP_AIRTABLE_DATABASE_ID,
  AIRTABLE_TOKEN: process.env.REACT_APP_AIRTABLE_TOKEN,
  WTN_APP_AIRTABLE_DATABASE_ID: process.env.REACT_APP_WTN_DATABASE_ID,
  WTN_APP_AIRTABLE_TOKEN: process.env.REACT_APP_WTN_TOKEN
};
